language: node_js
node_js:
  - 0.10
  - 0.11
  - 0.12
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - 5.1
  - 5.4
  - 5.8
  - iojs
  - iojs-v1.0.4

os:
  - linux

services:
  - redis-server
  - mongodb

notifications:
  email: false
